name: invariant_future
description: >-
  An extension type `IFuture` adjusting the typing of `Future`.
  The type parameter is invariant, and some member signatures
  have more strict static typing than `Future`.
version: 1.0.1
repository: https://github.com/eernstg/invariant_future

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  extension_type_unions: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
