name: safe_future
description: An extension type `SafeFuture` adjusting the API of `Future`.
version: 1.0.0
repository: https://github.com/eernstg/safe_future

environment:
  sdk: ^3.3.0-197.0.dev

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
